### ISSUE TITLE
Allow default boundary and capacity

### ISSUE THREAD

**Issue by shiffman** [CodingTrain/QuadTree#34]
In almost all cases the boundary is the size of the canvas so QuadTree could pick that up automatically. And we could also use a default capacity size of 8 (?).

**Comment by Dezzles** [comment]
I'm happy to take a look at this

**Comment by shiffman** [comment]
@Dezzles Can you explain more? (Sounds like a good idea but I'm not sure I understand completely.)

**Comment by Dezzles** [comment]
Instead of new QuadTree() creating a tree with default values, using something like 
QuadTree.withDefaults() 
That would invoke new default values
It would keep the constructor concise and predictable which I think is important

**Comment by Dezzles** [comment]
Quickly threw this together over lunch and put it in PR https://github.com/CodingTrain/QuadTree/pull/37
Take a look and let me know what you think?

**Comment by crhallberg** [comment]
Closing this issue since #37 resolves this issue
