### ISSUE TITLE
How I delete a point of the quadtree?

### ISSUE THREAD

**Issue by AndreAzevedoCoder** [CodingTrain/QuadTree#41]
Hey, I'm using your quadtree project in my game, (btw is in my github is called 'rogue'), but sometimes I need to delete some objects but I'm not realizing how to do that, could you help me?

**Comment by crhallberg** [comment]
Hello! Thank you for your patience! There is currently no implemented way to delete an object from a quadtree. It's a feature we're hoping to add soon!

One idea on how you could easily hack it into the library is to give each point a userData of `.deleted = true|false` and add a check for that to the query function. I'll try to make an example soon. If you beat me to it, feel free to share it back!

Hope this helps!

**Comment by crhallberg** [comment]
New `deleteInRange` method from #62.
