### ISSUE TITLE
error in QuadTree.closest() function

### ISSUE THREAD

**Issue by rentorious** [CodingTrain/QuadTree#49]
in this function when, after the "Limit to number of points in this QuadTree" comment, the lines are:
`if (this.length == 0) {
      return [];
    }
    if (this.length < count) {
      return this.points;
    }`

But there is no this.length.

I think it should be
`if (this.points.length == 0) {
      return [];
    }
    if (this.points.length < count) {
      return this.points;
    }`

**Comment by crhallberg** [comment]
Good looking out! This would certainly work as well. There is a c[lass getter for length](https://github.com/CodingTrain/QuadTree/blob/master/quadtree.js#L371) towards the bottom of the file. If this isn't working properly, I can incorporate your change!

**Comment by shiffman** [comment]
Just wanted to chime in here and say thank you @crhallberg for continuing to keep up with this repository!

**Comment by rentorious** [comment]
Actually, I just didn't notice the getter, sorry for any confusion :D
