### ISSUE TITLE
Rename main branch

### ISSUE THREAD

**Issue by crhallberg** [CodingTrain/QuadTree#55]
Hey @shiffman! I was hoping I could ask for a second of your time to rename the primary branch of this repository. It's very easy to do in the settings of this repository, which I don't have access to.

The p5 repository has gone with `main` and I also like `dev` but I leave it up to you.

Thanks!

**Comment by shiffman** [comment]
Hi @crhallberg, thanks for this reminder! I've been doing this with all of my repos as I work on them. I just upped your permissions, are you able to now? My preference is for `main` but don't feel super strongly about that!

**Comment by crhallberg** [comment]
Permissions look good! I'll take care of it now! Thank you!
