### ISSUE TITLE
QuadTree operations

### ISSUE THREAD

**Issue by MaanooAk** [CodingTrain/QuadTree#8]
A list of all the possible operations that can be implemented

- [x] Add point
- [x] Get points in range
- [x] Get all points (can be used to optimize the above) (forEach)
- [x] Get the closest to a point (given point x will return the inserted point y with smallest distance(x, y))
- [x] Remove point (#62)
- [x] Remove points in range (#62)
- [x] ~~Move point~~ [see this comment](https://github.com/CodingTrain/QuadTree/pull/42#issuecomment-951386948)
- [x] Merge quadtrees

(open for more suggestions)

**Comment by kleinesfilmroellchen** [comment]
what do you mean by "get the closest point"?

**Comment by kleinesfilmroellchen** [comment]
I suggest

- Higher-order functions:
    - Execute a function on all points
    - Execute a function on all points, and only if the function returns true for __all__ points, return true
    - Execute a function on all points, and only if the function returns true for __at least one__ point, return true
    - Return the first point where a given function (passed that point) returns true
    - "reduce"- like function?

**Comment by shiffman** [comment]
I just returned to this (quite a while later!) and merged a few pull requests so this issue can be updated to reflect the current status now!

**Comment by shiffman** [comment]
Thank you @crhallberg for continuing to help maintain this repo!
